# Generated by Django 5.1.5 on 2026-04-24 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_assigned_team_player_sold_for'),
        ('teams', '0002_team_colors_team_motto_team_team_slot_and_more'),
        ('tournaments', '0002_tournament_assigned_admins_tournament_auctioneer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='captain_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_for_teams', to='players.player'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(condition=models.Q(('captain_player__isnull', False)), fields=('tournament', 'captain_player'), name='unique_captain_player_per_tournament'),
        ),
    ]
