# Generated by Django 5.1.5 on 2026-04-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "sport_type",
                    models.CharField(
                        choices=[("cricket", "Cricket"), ("football", "Football")],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("live", "Live"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("purse_default", models.DecimalField(decimal_places=2, max_digits=12)),
                ("timer_seconds", models.PositiveIntegerField(default=90)),
                (
                    "min_increment",
                    models.DecimalField(decimal_places=2, default=100, max_digits=12),
                ),
                ("currency_label", models.CharField(default="INR", max_length=10)),
            ],
        ),
    ]
