# Generated by Django 5.1.5 on 2026-04-24 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='assigned_admins',
            field=models.ManyToManyField(blank=True, related_name='assigned_tournaments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='auctioneer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctioneer_tournaments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='first_prize',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tournament',
            name='logo',
            field=models.FileField(blank=True, upload_to='tournament_logos/'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='number_of_teams',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='tournament',
            name='participation_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tournament',
            name='playing_members',
            field=models.PositiveIntegerField(default=11),
        ),
        migrations.AddField(
            model_name='tournament',
            name='second_prize',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tournament',
            name='team_selection_method',
            field=models.CharField(choices=[('auction', 'By auction'), ('submission', 'By submission')], default='auction', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='third_prize',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tournament',
            name='total_members',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
