# Generated by Django 5.1.5 on 2026-04-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionround',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
