# Generated by Django 5.1.5 on 2026-04-23 21:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "sport_type",
                    models.CharField(
                        choices=[("cricket", "Cricket"), ("football", "Football")],
                        max_length=20,
                    ),
                ),
                ("role_position", models.CharField(max_length=80)),
                ("age", models.PositiveIntegerField()),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=80)),
                ("team_history", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("sold", "Sold"),
                            ("unsold", "Unsold"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("tournament", "name", "sport_type", "role_position", "age")
                },
            },
        ),
    ]
