# Generated by Django 5.1.5 on 2026-04-24 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('tournaments', '0002_tournament_assigned_admins_tournament_auctioneer_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('tournament', 'name')},
        ),
        migrations.AddField(
            model_name='player',
            name='profile_image',
            field=models.FileField(blank=True, upload_to='player_images/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='role_position',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
