# Generated by Django 5.1.5 on 2026-04-24 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_unique_together_player_profile_image_and_more'),
        ('teams', '0002_team_colors_team_motto_team_team_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='assigned_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='teams.team'),
        ),
        migrations.AddField(
            model_name='player',
            name='sold_for',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
